//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCasJsonManager.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VCasJsonManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   config.jsonが読み込めませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorConfigJsonRead {
            get {
                return ResourceManager.GetString("ErrorConfigJsonRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   config.jsonが書き込めませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorConfigJsonWrite {
            get {
                return ResourceManager.GetString("ErrorConfigJsonWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プリセットファイルが削除できませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorPresetDelete {
            get {
                return ResourceManager.GetString("ErrorPresetDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プリセットファイルが読み込めませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorPresetRead {
            get {
                return ResourceManager.GetString("ErrorPresetRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プリセットファイルが書き込めませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorPresetWrite {
            get {
                return ResourceManager.GetString("ErrorPresetWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブラウザが起動できませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorRunBrowser {
            get {
                return ResourceManager.GetString("ErrorRunBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バーチャルキャストが起動できませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorRunVirtualCast {
            get {
                return ResourceManager.GetString("ErrorRunVirtualCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   よく分からないエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorUnknown {
            get {
                return ResourceManager.GetString("ErrorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   よく分からないエラーが発生しました。アプリケーションを終了します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorUnknownFatal {
            get {
                return ResourceManager.GetString("ErrorUnknownFatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正しいマイリストのIDまたはURLを入力してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ValidationBadMylistId {
            get {
                return ResourceManager.GetString("ValidationBadMylistId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正しいニコニ立体のIDまたはURLを入力してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ValidationBadNico3dId {
            get {
                return ResourceManager.GetString("ValidationBadNico3dId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正しいniconareのIDまたはURLを入力してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ValidationBadNiconareId {
            get {
                return ResourceManager.GetString("ValidationBadNiconareId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正しいニコニコ動画のIDまたはURLを入力してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ValidationBadNicovideoId {
            get {
                return ResourceManager.GetString("ValidationBadNicovideoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正しいURLを入力してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ValidationBadUri {
            get {
                return ResourceManager.GetString("ValidationBadUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ValidationNoInput {
            get {
                return ResourceManager.GetString("ValidationNoInput", resourceCulture);
            }
        }
    }
}
